name: Create a comment on new issues

on: 
  issues:
    types: [opened]
    
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles
    
  comment-with-api: 
    runs-on: ubuntu-latest
    steps:
      - name: "comment from API"
        run: |
          gh api -X POST \
          repos/${USER}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body='Comment from the api'
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: ${{ github.event.issue.user.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
